# Generated by Django 5.2.2 on 2025-06-06 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SteganographyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('encrypt_message', 'Chiffrer un message dans une image'), ('decrypt_message', 'Déchiffrer un message depuis une image'), ('encrypt_pdf', 'Chiffrer un PDF en image'), ('decrypt_pdf', 'Déchiffrer une image en PDF')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='uploads/original/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='uploads/result/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('is_successful', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
